// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SyllableCounter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("total_syllables")]
        public long TotalSyllables { get; set; }

        [JsonProperty("word_count")]
        public long WordCount { get; set; }

        [JsonProperty("average_syllables_per_word")]
        public double AverageSyllablesPerWord { get; set; }

        [JsonProperty("words")]
        public Word[] Words { get; set; }
    }

    public partial class Word
    {
        [JsonProperty("word")]
        public string WordWord { get; set; }

        [JsonProperty("syllables")]
        public long Syllables { get; set; }
    }
}
